### ISSUE TITLE
[DEV-01] Seleccionar y Configurar el entorno de desarrollo

### ISSUE THREAD

**Issue by Leytonale** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tareafinal-grupo-5#1]
Establecer el entorno de desarrollo necesario para el proyecto, incluyendo la instalación de las herramientas y bibliotecas requeridas.

**Comment by Wleyton89** [comment]
Seleccionamos como entorno de desarrollo "Arduino IDE" para realizar el proyecto con la placa de desarrolo ESP32 por que:
- Es simple de usar gracias a su interfaz intuitiva.
- Tiene una gran comunidad y soporte por lo que cuenta con una gran cantidad de recursos y tutoriales e soluciones a problemas comunes en internet.
- Amplia compatibilidad.
- Portabilidad y flexibilidad al ser un IDE multiplataforma se puede usar en diferentes S.O y transferir el codigo a otras plataformas u lenguajes de programacion si fuera necesario.
