### ISSUE TITLE
[DEV-01.2] Instalar las bibliotecas necesarias para el ESP32, la pantalla OLED y el módulo de GPS

### ISSUE THREAD

**Issue by Leytonale** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tareafinal-grupo-5#3]
Descargar e instalar las bibliotecas requeridas para utilizar el ESP32, la pantalla OLED y el módulo de GPS.

**Comment by Wleyton89** [comment]
![Captura](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tareafinal-grupo-5/assets/108815579/e2254547-92da-4a83-82e2-f8dc88d7950e)

**Comment by Wleyton89** [comment]
![Captura2](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tareafinal-grupo-5/assets/108815579/9a4b383b-443c-4702-b676-1e608ea05805)

**Comment by Leytonale** [comment]
Se realizo la instalacion de la siguientes bibliotecas 
-Biblioteca "Arduino_ESP32_OTA" para la placa ESP32
-Biblioteca "Adafruit SSD1306" para la pantalla OLED SSD1306
-Biblioteca "TinyGPSPlus-ESP32"  para el módulo GPS NEO-6M
