### ISSUE TITLE
[DEV-09] Entrega del proyecto final funcionando

### ISSUE THREAD

**Issue by Leytonale** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tareafinal-grupo-5#34]
Realizar la entrega del proyecto final funcionando del GPS Tracker. En esta etapa, se espera que el proyecto esté completamente desarrollado y que todas las funcionalidades requeridas estén implementadas y probadas.

**Comment by alfredop37** [comment]
proyecto finalalizado y en funcionamiento.

**Comment by alfredop37** [comment]
![image](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tareafinal-grupo-5/assets/108839742/9ca3597b-835b-447e-8e83-e8b3a89da627)
