### ISSUE TITLE
[DEV-01.4] Elección de componentes para el proyecto

### ISSUE THREAD

**Issue by Leytonale** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tareafinal-grupo-5#35]
Realizar la selección de los componentes necesarios para llevar a cabo el proyecto GPS Tracker. Los componentes clave a considerar son la placa ESP32, la pantalla OLED y el módulo GPS. Se deben evaluar diferentes opciones en términos de especificaciones, disponibilidad y costo, y tomar una decisión fundamentada sobre qué componentes utilizar.

**Comment by alfredop37** [comment]
Necesitaremos los siguientes componentes para conectar nuestra placa de desarrollo ESP32 con la pantalla OLED y el módulo GPS NEO-6M: 

1. placa de desarrollo ESP32 
2. Módulo GPS NEO-6M 3. 
3. Pantalla OLED SSD1306 
4. Cables de conexión.

**Comment by alfredop37** [comment]
seleccion de componentes.
